#Deriving the latest base image
FROM python:3.8-slim-buster


#Labels as key value pair
LABEL Maintainer="docker.assignment.python3.8"


# Any working directory can be chosen as per choice like '/' or '/home' etc
WORKDIR /usr/app/src

#set ENV
ENV RESEARCH_PATH=/usr/app/src

#to COPY the remote file at working directory in container
COPY data/coding-environment-exercise.csv ./
COPY plotFromEnvironmentVar.py ./
COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

CMD [ "python3", "./plotFromEnvironmentVar.py"]
